### PR TITLE
_zunit: A completion for the `zunit' command

### PR DESCRIPTION
**Pull request by psprint**
Hello,
I thought that `zunit` command could have a completion. I've spiced up what I think is a good quality one. Any remarks?

### CODE REVIEW

**Comment by molovo** [comment]
@psprint I appreciate the work that you've put into this - but ZUnit has already got [a completion file](https://github.com/zunit-zsh/zunit/blob/master/zunit.zsh-completion) in the repository, and has done from the beginning. I'd be happy to merge any changes/upgrades you think may be necessary though.

**Comment by psprint** [comment]
Ahso, I've missed it because I was scanning the directory for underscore files. What do you think about adding an underscore to the file name? It's rather a common practice, e.g.: https://github.com/deadc0de6/dotdrop/tree/master/completion.

I see if something could be uplifted in the completion.

**Comment by molovo** [comment]
@psprint I'd rather keep the current naming tbh so that it's obvious what the file is, and it won't be confused with a command, particularly as zunit uses `_`-prefixed method names internally for private methods, and there is no `zunit` command in the repository until built from source.

The file needs to be copied/symlinked into `$fpath` anyway for it to work, and this is handled for the user by most installation methods. The manual process is also covered in the documentation: https://zunit.xyz/docs/getting-started/installation/#installing-manually

**Comment by psprint** [comment]
Oh, I see. Just noting that the file would work if renamed to the underscore version and symlinked/put into `$fpath`.

I've looked into the completion and it seems complete, actually more complete that the proposed one.

**Pull request closed without merging**
